/**
 * CSS Build Script - 合併 CSS 為 critical + main 兩個檔案
 *
 * 用法: node build-css.cjs
 *
 * critical.css = 首屏需要的樣式（navbar、hero、基礎排版）
 * main.css = 其他所有樣式（延遲載入）
 */

const fs = require('fs');
const path = require('path');

const CSS_DIR = path.join(__dirname, 'css');
const DIST_DIR = path.join(__dirname, 'css', 'dist');

// 首屏需要的 CSS（按載入順序）
const CRITICAL_FILES = [
  'variables.css',
  'base.css',
  'layout.css',
  'components.css',
  'sections-hero.css',
  'logo-3d.css',
  'hero-workflow.css',
  'animations-keyframes.css',
  'animations-stagger.css',
];

// 其他所有 CSS（按載入順序）
const MAIN_FILES = [
  'sections-services.css',
  'sections-solutions.css',
  'sections-tech-contact.css',
  'chatbot/chatbot-toggle.css',
  'chatbot/chatbot-window.css',
  'chatbot/chatbot-messages.css',
  'digital-workforce-layout.css',
  'digital-workforce-cards.css',
  'service-fullscreen-layout.css',
  'service-fullscreen-content.css',
  'service-quick-nav.css',
  'solutions-video-showcase.css',
  'website-analyzer.css',
  'website-analyzer-premium.css',
  'website-analyzer-report.css',
  'trust-section.css',
  'icons.css',
  'floating-line.css',
  // p1-marketing 子模組（展開 @import，避免連鎖請求）
  'p1-marketing/not-for-section.css',
  'p1-marketing/origin-story.css',
  'p1-marketing/real-scenario.css',
  'p1-marketing/workflow-layers.css',
  'p1-marketing/industries.css',
  'p1-marketing/guarantee.css',
  'p1-marketing/voice-collection.css',
  'p1-marketing/human-ai-boundary.css',
  'p1-marketing/output-preview.css',
  'p1-marketing/content-nurture.css',
  'p1-marketing/scarcity.css',
  'p1-marketing/maturity-quiz.css',
  'p1-marketing/responsive.css',
  'case-video.css',
];

function readCssFile(relativePath) {
  const fullPath = path.join(CSS_DIR, relativePath);
  if (!fs.existsSync(fullPath)) {
    console.warn(`  SKIP: ${relativePath} (not found)`);
    return '';
  }
  let content = fs.readFileSync(fullPath, 'utf-8');
  // 移除 @import 語句（已手動展開）
  content = content.replace(/@import\s+url\([^)]+\);?\s*/g, '');
  return `/* === ${relativePath} === */\n${content}\n`;
}

function buildBundle(files, outputName) {
  console.log(`\nBuilding ${outputName}...`);
  let bundle = `/* Auto-generated by build-css.cjs — DO NOT EDIT */\n`;
  let totalSize = 0;

  for (const file of files) {
    const content = readCssFile(file);
    bundle += content;
    totalSize += content.length;
    if (content) {
      console.log(`  + ${file}`);
    }
  }

  const outputPath = path.join(DIST_DIR, outputName);
  fs.writeFileSync(outputPath, bundle, 'utf-8');
  const sizeKB = (Buffer.byteLength(bundle, 'utf-8') / 1024).toFixed(1);
  console.log(`  => ${outputName}: ${sizeKB} KB`);
  return sizeKB;
}

// 建立 dist 目錄
if (!fs.existsSync(DIST_DIR)) {
  fs.mkdirSync(DIST_DIR, { recursive: true });
}

const criticalSize = buildBundle(CRITICAL_FILES, 'critical.css');
const mainSize = buildBundle(MAIN_FILES, 'main.css');

console.log(`\n✓ Done!`);
console.log(`  critical.css: ${criticalSize} KB (render-blocking, 首屏)`);
console.log(`  main.css: ${mainSize} KB (延遲載入)`);
console.log(`\nNext: update index.html to use css/dist/critical.css + css/dist/main.css`);
